### ISSUE TITLE
Problems with search_api_solr.settings.json file

### ISSUE THREAD

**Issue by argiepiano** [backdrop-contrib/search_api_solr#6]
The default file stored in folder `config` has two issues:
1. `"search_api_solr_tasks": "[]",` should be `"search_api_solr_tasks": [],`, since this key is supposed to hold an array. The quote marks makes it into a string.
2. The key `search_api_solr_last_optimize` is duplicated. This throws a warning in my IDE, saying that key duplication is a problem in JSON files.

**Comment by herbdool** [comment]
Actually, take a look at https://github.com/backdrop-contrib/search_api_solr/pull/7. There are bigger problems with those two. They shouldn't be in config. My PR fixes.

**Comment by argiepiano** [comment]
Closing this in favor of fixes in #7
