### ISSUE TITLE
Move non-configurable options from config to state

### ISSUE THREAD

**Issue by argiepiano** [backdrop-contrib/search_api_solr#8]
There are a few non-configurable options currently saved as json files that may be better suited for `state` saving. Reading and writing json files is expensive and slow, and may be causing some of the unusual behavior mentioned [here](https://backdrop.zulipchat.com/#narrow/stream/218635-Backdrop/topic/ConfigStorageReadException.20search_api_solr/near/402399562) in Zulip.

**Comment by herbdool** [comment]
@argiepiano I found the hash which is better stored in state (new PR). I'm not sure what else. The recently merged PR also set `last_optimize` to state.

**Comment by argiepiano** [comment]
@herbdool I left a comment. Also, please set the hash to state in update 1000.

**Comment by argiepiano** [comment]
Sorry, it won't be necessary to store this hash in update 1000, since this is done on page request

**Comment by argiepiano** [comment]
But... we should get rid of the config storage of the hash in that update hook.

**Comment by herbdool** [comment]
@argiepiano okay done.

**Comment by argiepiano** [comment]
LGTM
